name: cart-api
services: 
  nestjs:
    image: egatsak/egatsak-cart-api
    env_file:
      - .env
    ports: 
      - 80:${PORT} # expose-to-the-world : only-in-the-docker
    command: sh -c "npm run start:prod"
